version: '3'
services:
  peer:
    build: ./docker/peer
    ports:
      - "6443:6443"
  bootstrap:
    build: ./docker/bootstrap
    ports:
      - "6442:6442"
      - "8080:8080"
  rn:
    build: ./docker/rn
    ports:
      - "6446:6446"
      - "6480:6480"
  
