# === NodePK Makefile (Linux/macOS) ===

run:
	java -jar BeanNode.jar

wiz:
	java -jar WizCrypt.jar

reset:
	rm -rf data logs

run-screen:
	screen -S beannode -dm java -jar BeanNode.jar

help:
	@echo "Available Commands (Linux/macOS):"
	@echo "  make run          - Launch the BeanNode"
	@echo "  make wiz          - Run the WizCrypt CLI"
	@echo "  make reset        - Delete ./data and ./logs"
    @echo "  make run-screen   - Run the Node in a dettachable screen (must have screen installed)"
	@echo "  make help         - Show this help menu"
