##############################################################
#  Official BeanChain Node Configuration File (BEANNODE)     #
#  Version: v0.0.4.2                                         #
#  Node Role: BEANNODE (Standard Validator/Network Node)     #
#  --------------------------------------------------------  #
#  Update these values to configure node identity, network   #
#  participation, and local database paths.                  #
##############################################################


########## SECURITY & ACCESS ##########

#HEADLESS or PORTAL
mode=portal

# Path to encrypted private key (WIZ Key format)
#may hardcode after further testing in docker and VM flow
privateKeyPath=config.docs/wiz.txt

# Whether the WIZ Key uses Layer 2 encryption (WizCrypt)
encryptedWiz=true

# If true, user must enter password to decrypt WizKey at launch
requirePass=true

# Optional admin override password (used instead of prompt if requirePass = false)
# If encryptedWiz = false, this is ignored.
adminPass=admin


#Optional local CLI interface Configuration
#If true local access with token is open 
openLocal=false
#token for private node commmand access 
token.cli=YOUR_TOKEN


########## NETWORK SETTINGS ##########

# IP address to bind this node to (0.0.0.0 binds to all interfaces)
bindAddress=0.0.0.0

# Port that this node will open to accept connections from other peers
networkPort=6442

# Port of the bootstrap (GPN or PN) node this client will connect TO
# (used when isBootstrapNode=false)
peerPort=6442

# Whether this node is the Genesis Public Node (GPN !!/ bootstrap node) GPN ONLY RIGHT NOW!!
isBootstrapNode=false

# IP address of the bootstrap node (required if not a bootstrap node)
bootstrapIp=66.179.82.188

# Synchronization mode
# Options: FULL — receives blocks and TXs; TX_ONLY — receives TXs only
syncMode=FULL

# Declared node type (used in handshake)
# Options: BEANNODE, CEN, MODULE, RN, etc.
nodeType=BEANNODE

# Whether this node exposes public-facing API endpoints
isPublicNode=true


########## DATABASE SETTINGS ##########

# Database file names (stored inside dbRoot directory)
chainDB=chainDB
stateDB=stateDB
mempoolDB=mempoolDB
rejectedDB=rejectedDB
layer2DB=layer2DB




